version: "3"
services:
  prom:
    build: .
    restart: always
    ports:
      - 9191:9090
    depends_on:
      - exporter
  exporter:
    image: prom/node-exporter:latest
    restart: always
    ports:
      - "9111:9100"